---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
    - role: pip-packages-install

- hosts: master
  become: yes
  environment:
    K8S_AUTH_KUBECONFIG: ~{{ ansible_user }}/.kube/config
    K8S_AUTH_HOST: https://{{ master_ip }}:6443
    HELM_KUBEAPISERVER: https://{{ master_ip }}:6443
  roles:
    - role: k3s/master
    - role: k8s-dashboard
    - role: helm-install
    - role: ingress-controllers/traefik
    - role: cert-manager
    - role: k8s-dashboard
    - role: kube-prometheus-stack

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: localhost
  gather_facts: false
  connection: local
  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"
    K8S_AUTH_HOST: https://{{ master_ip }}:6443
  become: yes
  roles:
  # - role: k8s-manifests/k8s-dashboard-remote-access
