---

- name: Install python3
  package:
    name: python3
    state: present

- name: Install python3-pip
  package:
    name: python3-pip
    state: present

- name: Install kubernetes python package
  pip:
    name: kubernetes

- name: Install PyYAML python package
  pip:
    name: PyYAML

- name: Install jsonpatch python package
  pip:
    name: jsonpatch

- name: Install pyhelm python package
  pip:
    name: pyhelm

- name: Install grpcio python package
  pip:
    name: grpcio
